name: 🚀 Deploy website on push
on:
  workflow_dispatch:

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v3

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ftp.stager.website
          username: ${{ secrets.ftp_username }}
          password: ${{ secrets.ftp_password }}
          protocol: ftps
          port: 21
          server-dir: ./stage-cat.stager.website/
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/wp-content/plugins/**
            **/wp-content/upgrade/**